language: ruby
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- jruby-18mode
- jruby-19mode
- rbx
deploy:
  provider: heroku
  api_key:
    secure: bS/Ks9dPfCB7zJJ+sGtvCwxrX+/6BnXSt6SmgCfI0p1Fs7C/3goyPFg6bBsJezYAGlgRoxFB7hwRE4IEcx81KetYi9YMj0tmmxpXRYwxzd8Fj/O9r6AHdNfTMc+nvwrhb+s9HEYKcs5g+aUR5FbcIJAhKLbAEwWYIbpf16Uy9bc=
  app: toonssample
  on:
    repo: nguyen-thanh-tungb/sample_app
